---
- name: DEBUG | Show credential we are working on
  when:
    - ansible_verbosity >= 1
  ansible.builtin.debug:
    msg: "Processing credential {{ __this_credential.name }}"

- name: Update credential
  ansible.controller.credential:
    controller_host: "{{ aap_hostname }}"
    controller_username: "{{ aap_username }}"
    controller_password: "{{ aap_password }}"
    validate_certs: "{{ aap_validate_certs }}"
    request_timeout: 10.0
    credential_type: "Ansible Galaxy/Automation Hub API Token"
    name: "{{ __this_credential.name }}"
    organization: "{{ __this_credential.organization | default(omit) }}"
    team: "{{ __this_credential.team | default(omit) }}"
    user: "{{ __this_credential.user | default(omit) }}"
    description: "{{ __this_credential.description | default('') }}"
    inputs:
      url: "{{ __this_credential.inputs.url }}"
      token: "{{ ansible_facts.aap_token.token }}"


...
